name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.10"
            req: dev_requirements.txt
            coverage: "false"
          - python: "3.11"
            req: dev_requirements_np2x.txt
            coverage: "true"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common ffmpeg

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py${{ matrix.python }}-${{ hashFiles(matrix.req) }}

      - name: Install Python dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip wheel
          pip install -r ${{ matrix.req }}

      - name: Run pytest
        run: |
          . .venv/bin/activate
          if [ "${{ matrix.coverage }}" = "true" ]; then
            pytest --cov=. --cov-report=xml
          else
            pytest
          fi

      - name: Upload coverage to Codecov
        if: matrix.coverage == 'true'
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: python-${{ matrix.python }}
